

<?php
/**
 * Created by PhpStorm.
 * User: artphotografie
 * Date: 2016/02/14
 * Time: 12:39 PM
 */
?>

<?php

/**
 *
 * Tinymce styple
 *
 * */
use FWAP\Helpers\Assets;
?>

<script src="<?php echo URL; ?>Public/bootstrap/jQuery.js"></script>
<script src="<?php echo URL; ?>Public/bootstrap/js/bootstrap.min.js"></script>
<script src="<?php echo URL; ?>Public/tinymce/tinymce.min.js"></script>
<script src="<?php echo URL; ?>Public/tinymce/jquery.tinymce.min.js"></script>
<script src="<?php echo URL; ?>Public/Js/tinymce.init.js"></script>
<script src="<?php echo URL; ?>Public/Js/jquery.validate.js"></script>

<footer class="panel-footer modal-footer ">
    <?php \FWAP\Library\Copyright::copyright(2015, 'APWEB FRAMWORK'); ?>
</footer>
</body>
</html>

